### ISSUE TITLE
Submission folder has all black images

### ISSUE THREAD

**Issue by shubhamgoel27** [vdurnov/xview2_1st_place_solution#3]
In the individual model output folders, I'm getting the correct outputs, i.e. there are buildings having different colors associated with their damage values. 

But the submissions folder being created has all black images. I tried reading them using `cv2` and all pixel values are indeed 0. Not sure how to proceed.

**Comment by vdurnov** [comment]
Hi, Please ready contest description carefully. For final submission used only 0-4 byte values - of course they are black/dark in image viewer. You can increase contrast or use another viewer.

**Comment by jacksteussie** [comment]
@vdurnov you literally cannot increase the contrast if all of the pixel values are zero
