### ISSUE TITLE
what if I only have one image to predict?

### ISSUE THREAD

**Issue by algo-scope** [vdurnov/xview2_1st_place_solution#4]
In the part of prediction, for example predict50cls.py, the script would find files with 'pre' and 'post' in their names. But when I only have one post disaster image, what should I do to use your model?

**Comment by vdurnov** [comment]
Model is not designed for this. It expects 2 images as input (pre and post). It is defined in competition rules.

**Comment by algo-scope** [comment]
I wonder if I copied the post image then rename it to 'pre', would the model still work?

**Comment by vdurnov** [comment]
It will give bad predictions. Model should see both pre and post images to investigate changes after disaster
