### ISSUE TITLE
trained model weights link is not working

### ISSUE THREAD

**Issue by nimaafshar** [vdurnov/xview2_1st_place_solution#9]
Hi

I am trying to use your model but the link in `README.md` to trained model weights [https://vdurnov.s3.amazonaws.com/xview2_1st_weights.zip](https://vdurnov.s3.amazonaws.com/xview2_1st_weights.zip) is not working and returns access denied.

response:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>S1VMK858D0ATDQT5</RequestId>
<HostId>fgY53YOWp206iRsWX9lTUqV3sy35GN5gEeRuq2Hgv8/yZZRaEwPepJLPsO4yqcmC9DzqOGneeA0=</HostId>
</Error>
```

can you update this link?

**Comment by suhail017** [comment]
You can download the files from the release tags of the xView2 repo  [https://github.com/DIUx-xView/xView2_first_place/releases/tag/final](url)

**Comment by mmuneeburahman** [comment]
@suhail017 There exists nothing on this link, can you provide any other source?

**Comment by suhail017** [comment]
https://github.com/DIUx-xView/xView2_first_place/releases

**Comment by Astraioss** [comment]
> https://github.com/DIUx-xView/xView2_first_place/releases

I'm running into some issues when trying to implement the weightings into the xView solution, I think its mainly to do with the file type. Adding either the tar.gz or the .tar file into the weights folder causes a variation of this error:

Changed paths for weights and file names in predict34_loc.py for example:
`test_dir = 'test/images'
pred_folder = 'pred34_loc'
models_folder = '/content/drive/MyDrive/'

if __name__ == '__main__':
    t0 = timeit.default_timer()

    makedirs(pred_folder, exist_ok=True)
    
    os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
    # os.environ["CUDA_VISIBLE_DEVICES"] = sys.argv[1]

    # cudnn.benchmark = True

    models = []

    for seed in [0, 1, 2]:
        snap_to_load = 'split-weights-aa'.format(seed)
        model = Res34_Unet_Loc().cuda()
        model = nn.DataParallel(model).cuda()
        print("=> loading checkpoint '{}'".format(snap_to_load))
        checkpoint = torch.load(path.join(models_folder, snap_to_load), map_location='cpu')
        loaded_dict = checkpoint['state_dict']
        sd = model.state_dict()
        for k in model.state_dict():
            if k in loaded_dict and sd[k].size() == loaded_dict[k].size():
                sd[k] = loaded_dict[k]
        loaded_dict = sd
        model.load_state_dict(loaded_dict)
        print("loaded checkpoint '{}' (epoch {}, best_score {})"
                .format(snap_to_load, checkpoint['epoch'], checkpoint['best_score']))
        model.eval()
        models.append(model)`


With error:
` File "predict34_loc.py", line 49, in <module>
    checkpoint = torch.load(path.join(models_folder, snap_to_load), map_location='cpu')
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.`
